<?php

namespace Miladshm\ControllerHelpers\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Miladshm\ControllerHelpers\Models\TestModel;

/** @mixin TestModel */
class TestModelResource extends JsonResource
{
    /**
     * @param Request $request
     * @return array
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'code' => $this->code,
            'status' => $this->status,
            'order' => $this->order,
            'count' => $this->count,
            'parent_id' => $this->parent_id,
            'name' => $this->name,

            'rels_count' => $this->whenCounted('rels'),
            // Relations
            'parent' => new ParentModelResource($this->whenLoaded('parent')),
            'rels' => RelResource::collection($this->whenLoaded('rels')),
            'deleted_at' => $this->deleted_at,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }

    /**
     * Customize the pagination information for the resource.
     *
     * @param Request $request
     * @param array $paginated
     * @param array $default
     * @return array
     */
    public function paginationInformation($request, $paginated, $default)
    {
        $default['links']['custom'] = 'https://example.com';

        return $default;
    }

    public static function collection($resource)
    {
        return parent::collection($resource); // TODO: Change the autogenerated stub
    }


}
